# language: haskell

sudo: required

env:
 - GHCVER=7.10.3 CABALVER=1.24
 - GHCVER=8.0.2 CABALVER=1.24
 - GHCVER=7.10.3 CABALVER=2.0
 - GHCVER=8.0.2 CABALVER=2.0
 # Disable 8.2 for now.
 # - GHCVER=8.2.2 CABALVER=1.24

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install hoogle cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal update

 # These sandbox commands are doing manually what mafia would do when building itself.
 - cabal sandbox init
 - cabal sandbox add-source lib/disorder/disorder-core
 - cabal sandbox add-source lib/disorder/disorder-corpus
 - cabal sandbox add-source lib/p
 - cabal sandbox add-source lib/twine
 - cabal sandbox add-source lib/x/x-eithert
 - cabal sandbox add-source lib/x/x-exception
 - cabal sandbox add-source lib/x/x-optparse

script:
 - cabal install --dependencies-only --enable-tests
 - cabal configure --enable-tests
 - cabal build
 - dist/build/test/test
 - dist/build/test-io/test-io
 - dist/build/test-cli/test-cli
 - cabal haddock
 - cabal sdist
